stages:
    - test-python
    - build-docs

python_unit_tests:
  image: themattrix/tox
  stage: test-python
  script:
  - export PYTHONPATH=$PYTHONPATH:$CI_PROJECT_DIR
  - pip install --upgrade pip
  - pip install -r requirements_dev.txt
  - pip install -U tox
  - tox

pages:
  image: seriallab/python3.6dev
  stage: build-docs
  script:
  - export PYTHONPATH=$PYTHONPATH:$CI_PROJECT_DIR
  - pip install sphinx recommonmark sphinx_rtd_theme pygments ipython
  - cd docs/
  - make html
  - mv _build/html/ public/
  artifacts:
      paths:
      - public
      expire_in: 1h

######################
# To implement, uncomment and put a secret
# variable in your CI config for your PyPI account
# This will push all taged builds to PyPI.
######################
#deploy_pypi:
#  image: seriallab/python3.5dev
#  stage: pypi
#  environment:
#    name: deployment
#    url: https://pypi.org/
#  script:
#    - echo "[distutils]" >> ~/.pypirc
#    - echo "index-servers = " >> ~/.pypirc
#    - echo "[pypi]" >> ~/.pypirc
#    - echo "username=$PYPI_USER" >> ~/.pypirc
#    - echo "password=$PYPI_PASSWORD" >> ~/.pypirc
#    - python setup.py check sdist bdist_wheel upload
#    - rm ~/.pypirc
#  only:
#    - tags


